### ISSUE TITLE
integrate pyMT5 with Strategy Testetr

### ISSUE THREAD

**Issue by jalalahmadi201820** [devcartel/devcartelgateway64#2]
hi
i'm trying to integrate python with mt5 strategy tester.
my question is that is it posssible to connect pyMT5 with Strategy Tester ? 

i'll really appreciate you.

**Comment by wiwat-tharateeraparb** [comment]
Sorry we don't support Strategy Tester.

**Comment by TheSnowGuru** [comment]
I just published this one, an it cant do test but you can do other cool stuff:
https://github.com/TheSnowGuru/PyTrader-python-mt5-trading-api-connector

**Comment by jalalahmadi201820** [comment]
thank you very much.
