### ISSUE TITLE
สงสัยเกี่ยวกับ type stop  order

### ISSUE THREAD

**Issue by NantipatSoftEn** [devcartel/devcartelgateway64#4]
กรณี type stop  order  กด place  order **แล้ว message order จะไม่ตอบทันที**(ใช้ pymt5) แต่จะต้องรอราคาให้ไปแตะราคา stop ของ order นั้นถึงจะมี message ออกมา  แต่ในกรณีของ limit  จะมี **message order ตอบกลับมาทันที**  ผมเลยสงสัยว่าทำไมมันถึงแตกต่างกันเพราะอะไร?   :pray: ขอบคุณล่วงหน้าครับ

**Comment by wiwat-tharateeraparb** [comment]
อันนี้เป็นธรรมดาของ stop order type ครับ ซึ่งเมื่อวาง stop order แล้ว order จะ activate เมื่อราคาไปถึง trigger price ครับ
